# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test should run
      id: should_run
      run: |
        echo SKIPPING=$(if [[ "${{ github.event.head_commit.message }}" == "auto update" ]]; then echo "false"; else echo "true"; fi) >> $GITHUB_OUTPUT
    - name: Install dependencies
      if: ${{ steps.should_run.outputs.SKIPPING == 'true' }}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      if: ${{ steps.should_run.outputs.SKIPPING == 'true' }}
      run: |
        python get-price-info.py > price-info.json
    - name: git operation
      if: ${{ steps.should_run.outputs.SKIPPING == 'true' }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add price-info.json
        git commit -m "auto update"
        git push
    # - uses: stefanzweifel/git-auto-commit-action@v5
    #   name: Commit and push changes
    #   with:
    #     commit_message: "Automated update of browserslist-db"
    #     push_options: '--force'
    #     # No explicit repository URL, using GITHUB_TOKEN by default 
