# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Daily Build

on:
  schedule:
    - cron: '11 20 * * *'
  push:
    branches: [ "master" ]
    tags-ignore:
      - "*"
    path:
      - '*.py'
      - '*.sh'
      - '.github/workflow/*.yml'
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test should run
      id: should_run
      run: |
        echo SKIPPING=$(if [[ "${{ github.event.head_commit.message }}" == "auto update" ]]; then echo "false"; else echo "true"; fi) >> $GITHUB_OUTPUT
    - name: Install dependencies
      if: ${{ steps.should_run.outputs.SKIPPING == 'true' }}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run pre script
      run: cat price-info.json
    - name: Run script
      if: ${{ steps.should_run.outputs.SKIPPING == 'true' }}
      run: |
        ./run.sh
    - name: Run pre script
      if: always()
      run: cat price-info.json
    - name: git operation
      if: ${{ steps.should_run.outputs.SKIPPING == 'true' }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add *.json
        git add json-data/*.json
        git add README.md
        git commit -m "auto update"
        git push
